version: '3.8'
services:
  workspace:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-20
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
